controller_names:
  - scaled_joint_trajectory_controller
  - joint_trajectory_controller


scaled_joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - ur5e__shoulder_pan_joint
    - ur5e__shoulder_lift_joint
    - ur5e__elbow_joint
    - ur5e__wrist_1_joint
    - ur5e__wrist_2_joint
    - ur5e__wrist_3_joint


joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: false
  joints:
    - ur5e__shoulder_pan_joint
    - ur5e__shoulder_lift_joint
    - ur5e__elbow_joint
    - ur5e__wrist_1_joint
    - ur5e__wrist_2_joint
    - ur5e__wrist_3_joint